academica/urls.py
from django.conf.urls import include, url
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.views import password_change
from academica import views


urlpatterns = [
    url(r'^alumno_notas/$', views.reporte_alumno_notas, name='alumno_notas'),
    url(r'^reporte_quimestre/$', views.reporte_quimestre, name='reporte_quimestre'),
    url(r'^reporte_matricula/$', views.reporte_matricula, name='reporte_matricula'),
    url(r'^alumnos/(?P<tipo_reporte>\w+)/$', views.alumnos, name='alumnos'),

    url(r'^authcheck/$', views.authcheck, name='authcheck'),
    url(r'^cambiar_password/password_changed/$', views.password_changed, name='password_changed'),
    url(r'^cambiar_password/$', password_change,
        {'template_name': 'academica/cambiar_password.html',
            'post_change_redirect': 'password_changed/',
            'password_change_form': PasswordChangeForm},
            name='cambiar_password'),

    url(r'^perfil_profesor/$', views.perfil_profesor, name='perfil_profesor'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^clases/$', views.clases, name='clases'),
    url(r'^clase/(?P<clase_id>\d+)/(?P<periodo_id>\d+)/$', views.clase_alumnos, name='clase_alumnos'),
    url(r'^clase/(?P<clase_id>\d+)/$', views.clase_periodos, name='clase_periodos'),
    url(r'^editar_notas/$', views.editar_notas, name='editar_notas'),

    url(r'^matricular_grupo/$', views.matricular_grupo, name='matricular_grupo'),
    url(r'^publicar_nota/$', views.publicar_nota, name='publicar_nota'),
    url(r'^esconder_nota/$', views.esconder_nota, name='esconder_nota'),
]

aradiel/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from inicio import views


urlpatterns = [
    url(r'^$', views.inicio, name="inicio_redirect"),
    url(r'^ameliagallegos/', include('inicio.urls', namespace='inicio')),
    url(r'^academica/', include('academica.urls', namespace='academica')),
    url(r'^admin/', include(admin.site.urls)),
]

inicio/urls.py
from django.conf.urls import include, url

from inicio import views


urlpatterns = [
    url(r'^$', views.inicio, name="inicio_redirect"),
    url(r'^inicio/$', views.inicio, name='inicio'),
    url(r'^colegio/$', views.colegio, name='colegio'),
    url(r'^docentes/$', views.docentes, name='docentes'),
    url(r'^estudiantes/$', views.estudiantes, name='estudiantes'),
    url(r'^blog/$', views.blog, name='blog'),
    url(r'^sislogin/$', views.sislogin, name='sislogin'),
]

academica/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.forms import ModelForm, TextInput, Select, PasswordInput
from django.contrib.auth.forms import PasswordChangeForm

from academica.models import Perfil_Profesor, Periodo, Nivel

"""
class FormCambiarPassword(PasswordChangeForm):

	class Meta:
		widgets = {
			'old_password': PasswordInput(attrs={'class': 'form-control'}),
			'new_password1': PasswordInput(attrs={'class': 'form-control'}),
			'new_password2': PasswordInput(attrs={'class': 'form-control'})
		}
"""


class NumberInput(TextInput):
	input_type = 'number'


class FormReportePeriodo(forms.Form):
	periodos_obj = Periodo.objects.all()
	periodos = []
	for p in periodos_obj:
		periodos.append((p.id, p.nombre_periodo))

	niveles_obj = Nivel.objects.all()
	niveles = []
	for n in niveles_obj:
		niveles.append((n.id, n.nombre))

	cedula = forms.CharField(required=True, max_length=10, widget=TextInput(attrs={'class': 'form-control', 'id': 'cedula'}))
	periodo = forms.ChoiceField(choices=periodos, widget=Select(attrs={'class': 'form-control'}))
	nivel = forms.ChoiceField(choices=niveles, widget=Select(attrs={'class': 'form-control', 'name': 'nivel'}))


class FormReporteQuimestre(forms.Form):

	niveles_obj = Nivel.objects.all()
	niveles = []
	for n in niveles_obj:
		niveles.append((n.id, n.nombre))

	cedula = forms.CharField(required=True, max_length=10, widget=TextInput(attrs={'class': 'form-control', 'id': 'cedula'}))
	nivel = forms.ChoiceField(choices=niveles, widget=Select(attrs={'class': 'form-control', 'name': 'nivel'}))	
	ano = forms.CharField(required=True, max_length=4, widget=TextInput(attrs={'class': 'form-control', 'id': 'ano'}))
	quimestre = forms.IntegerField(required=True, max_value=4, widget=NumberInput(attrs={'class': 'form-control', 'id': 'quimestre', 'max': '2', 'min': '1'}))


class FormPerfilProfesor(forms.ModelForm):

	def __init__(self, *args, **kwargs):
		super(FormPerfilProfesor, self).__init__(*args, **kwargs)
		self.fields['titulo'].required = False
		self.fields['num_contacto'].required = False

	class Meta:
		model = Perfil_Profesor
		fields = ('titulo', 'num_contacto')
		widgets = {
			'num_contacto': TextInput()
		}


class FormEditarNotas(forms.Form):

	tareas = forms.FloatField(required=False, max_value=10, min_value=0,
		widget=NumberInput(attrs={'id': 'form_tareas', 'step': '0.1', 'max': '10', 'min': '0'}))
	actividades_individuales = forms.FloatField(required=False, max_value=10, min_value=0,
		widget=NumberInput(attrs={'id': 'form_act_ind', 'type': 'number', 'step': '0.1', 'max': '10', 'min': '0'}))
	actividades_grupales = forms.FloatField(required=False, max_value=10, min_value=0,
		widget=NumberInput(attrs={'id': 'form_act_gru', 'type': 'number', 'step': '0.1', 'max': '10', 'min': '0'}))
	lecciones = forms.FloatField(required=False, max_value=10, min_value=0,
		widget=NumberInput(attrs={'id': 'form_lecciones', 'type': 'number', 'step': '0.1', 'max': '10', 'min': '0'}))
	pruebas = forms.FloatField(required=False, max_value=10, min_value=0,
		widget=NumberInput(attrs={'id': 'form_pruebas', 'type': 'number', 'step': '0.1', 'max': '10', 'min': '0'}))
	clase = forms.CharField(required=False,
		widget=TextInput(attrs={'id': 'form_clase'}))
	alumno = forms.CharField(required=False,
	    widget=TextInput(attrs={'id': 'form_alumno'}))
	periodo = forms.CharField(required=False,
		widget=TextInput(attrs={'id': 'form_periodo'}))


class FormMatricularGrupo(forms.Form):

	niveles_obj = Nivel.objects.all()
	niveles = []
	for n in niveles_obj:
		niveles.append((n.id, n.nombre))

	ano_lectivo = forms.IntegerField(required=True, max_value=9999, min_value=0, initial="2015", widget=NumberInput(attrs={'name': 'ano_lectivo'}))
	nivel = forms.ChoiceField(choices=niveles, widget=Select(attrs={'name': 'nivel'}))

academica/views.py
# -*- coding: utf-8 -*-
from django.contrib import auth
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse

from .utils import obtener_perfil_profesor, obtener_clases_profesor, obtener_alumnos_clase,\
                obtener_fila_alumno_notas, obtener_editar_valor_nota, obtener_clases_nivel, \
                obtener_notas_alumno, obtener_notas_quimestre
from .models import Clase, Periodo, Perfil_Profesor, Alumno, Nivel, Matricula, Nota
from .forms import FormPerfilProfesor, FormEditarNotas, FormReportePeriodo, FormMatricularGrupo, FormReporteQuimestre


def authcheck(request):
	# standard auth de Django. Para usuarios especiales
	username = request.POST.get('username', '')
	password = request.POST.get('password', '')
	user = auth.authenticate(username=username, password=password)
	if user is not None:
		auth.login(request, user)
		return redirect('academica:clases')
	else:
		return redirect('inicio:sislogin')


def password_changed(request):
	template = 'academica/password_changed.html'
	context = {}
	return render(request, template, context)


def perfil_profesor(request):
	template = "academica/form_perfil_profesor.html"
	perfil_actual = get_object_or_404(Perfil_Profesor, usuario=request.user)
	if request.method == "POST":
		form = FormPerfilProfesor(request.POST, instance=perfil_actual)
		if form.is_valid():
			form.save()
			return redirect('academica:perfil_profesor')
		else:
			return redirect('academica:clases')
	else:
		form_editar_perfil = FormPerfilProfesor()
		context = {'form_editar_perfil': form_editar_perfil, 'perfil_actual': perfil_actual}

		return render(request, template, context)


@login_required
def clases(request):
	template = "academica/lista_clases.html"
	perfil_profesor = obtener_perfil_profesor(request.user)
	clases_profesor = obtener_clases_profesor(perfil_profesor)
	context = {'clases_profesor': clases_profesor}
	return render(request, template, context)


@login_required
def clase_periodos(request, clase_id):
	template = "academica/clase_periodos.html"
	clase = get_object_or_404(Clase, id=clase_id)
	periodos = Periodo.objects.all()
	context = {'periodos': periodos,
		       'clase': clase}
	return render(request, template, context)


# View con las Notas de cada alumno
@login_required
def clase_alumnos(request, clase_id, periodo_id):
	template = "academica/clase.html"
	periodo = get_object_or_404(Periodo, id=periodo_id)
	clase = get_object_or_404(Clase, id=clase_id)
	alumnos_clase = obtener_alumnos_clase(clase)
	lista_datos = []
	for alumno in alumnos_clase:
		notas_alumno = obtener_fila_alumno_notas(alumno, clase, periodo)
		lista_datos.append(notas_alumno)
	form_editar_notas = FormEditarNotas
	context = {'clase': clase, 'periodo': periodo, 'lista_datos': lista_datos,
	           'form_editar_notas': form_editar_notas}

	return render(request, template, context)


@login_required
def editar_notas(request):
	if request.method == "POST":
		form = FormEditarNotas(request.POST)
		if form.is_valid():
			tareas = form.cleaned_data['tareas']
			actividades_individuales = form.cleaned_data['actividades_individuales']
			actividades_grupales = form.cleaned_data['actividades_grupales']
			pruebas = form.cleaned_data['pruebas']
			lecciones = form.cleaned_data['lecciones']

			clase = Clase.objects.get(pk=form.cleaned_data['clase'])
			alumno = Alumno.objects.get(pk=form.cleaned_data['alumno'])
			periodo = Periodo.objects.get(pk=form.cleaned_data['periodo'])

			obtener_editar_valor_nota(clase=clase, periodo=periodo, alumno=alumno, tipo="tareas", valor=tareas)
			obtener_editar_valor_nota(clase=clase, periodo=periodo, alumno=alumno, tipo="act_ind", valor=actividades_individuales)
			obtener_editar_valor_nota(clase=clase, periodo=periodo, alumno=alumno, tipo="act_gru", valor=actividades_grupales)
			obtener_editar_valor_nota(clase=clase, periodo=periodo, alumno=alumno, tipo="pruebas", valor=pruebas)
			obtener_editar_valor_nota(clase=clase, periodo=periodo, alumno=alumno, tipo="lecciones", valor=lecciones)

			return redirect('academica:clase_alumnos', clase.id, periodo.id)


def logout(request):
    auth.logout(request)  # Logout el user guardado en Request
    return redirect('inicio:sislogin')


def matricular_grupo(request):
	template = "academica/matricular_grupo.html"

	cedulas = request.session['cedulas']
	alumnos = []

	if request.method == "POST":
		form = FormMatricularGrupo(request.POST)

		if form.is_valid():
			ano_lectivo = form.cleaned_data["ano_lectivo"]
			nivel_id = form.cleaned_data["nivel"]
			
			nivel_obj = Nivel.objects.get(id=nivel_id)
			matriculas_creadas = []

			for c in cedulas:
				try:
					alumnos.append(Alumno.objects.get(cedula=c))
				except:
					pass

			for a in alumnos:
				if Matricula.objects.filter(nivel=nivel_obj, ano_lectivo=ano_lectivo, alumno=a).exists():
					print("matricula de alumno %s ya existe" % (a.nombre))
				else:
					nueva_matricula = Matricula(nivel=nivel_obj, ano_lectivo=ano_lectivo, alumno=a)
					nueva_matricula.save()
					matriculas_creadas.append(nueva_matricula)

			template = "academica/matriculas_creadas.html"
			context = {'matriculas_creadas': matriculas_creadas}

			return render(request, template, context)
		
		else:

			return HttpResponse("no valid")

	else:
		form = FormMatricularGrupo()

	for c in cedulas:
		try:
			alumnos.append(Alumno.objects.get(cedula=c))
		except:
			pass

	context = {'alumnos': alumnos, 'form': form}

	return render(request, template, context)


def publicar_nota(request):

	nota_id = request.GET.get("id", '')	

	if nota_id:
		nota = Nota.objects.get(id=nota_id)
		nota.publicada = True
		nota.save()
		return HttpResponse('Nota marcada como publica')
	else:
		return HttpResponse(status_code=500)


def esconder_nota(request):

	nota_id = request.GET.get("id", '')

	if nota_id:
		nota = Nota.objects.get(id=nota_id)
		nota.publicada = False
		nota.save()
		return HttpResponse('No marcada como no publica')
	else:
		return HttpResponse(status_code=500)


def alumnos(request, tipo_reporte):
	template = "academica/alumnos.html"

	if tipo_reporte == "quimestral":
		form = FormReporteQuimestre
	else:
		form = FormReportePeriodo
	context = {'form': form, 'tipo': tipo_reporte}
	return render(request, template, context)


def reporte_alumno_notas(request):
	template = "academica/alumno_notas.html"

	alumno = get_object_or_404(Alumno, pk=int(request.GET.get("cedula", 0)))
	nivel = get_object_or_404(Nivel, pk=request.GET.get("nivel", ""))
	periodo = get_object_or_404(Periodo, pk=request.GET.get("periodo", ""))
	clases = obtener_clases_nivel(nivel)
	notas = obtener_notas_alumno(alumno, clases, periodo)
	context = {'nivel': nivel, 'alumno': alumno, 'periodo': periodo, 'clases': clases, 'notas': notas}

	return render(request, template, context)


def reporte_quimestre(request):
	template = "academica/reporte_quimestral.html"
	
	nivel = get_object_or_404(Nivel, pk=request.GET.get("nivel", ""))
	alumno = get_object_or_404(Alumno, pk=request.GET.get("cedula", ""))
	ano = request.GET.get("ano", "")
	quimestre = request.GET.get("quimestre", "")

	periodos = Periodo.objects.filter(ano_lectivo=ano, quimestre=quimestre)
	clases = obtener_clases_nivel(nivel)
	
	notas = obtener_notas_quimestre(alumno, clases, periodos)	

	context = {'nivel': nivel, 'alumno': alumno, 'quimestre': quimestre, 'clases': clases, 'notas': notas, 'ano': ano}

	return render(request, template, context)


def reporte_matricula(request):
	template = "academica/reporte_matricula.html"

	ids_matriculas = request.session['matriculas']	

	matriculas = []
	for id_matricula in ids_matriculas:
		matricula_obj = get_object_or_404(Matricula, id=id_matricula)
		matriculas.append(matricula_obj)

	context = {'matriculas': matriculas}
	
	return render(request, template, context)

academica/templates/academica/admin_app_name.html
Sistema Académico

academica/templates/academica/alumno_notas.html
<!DOCTYPE html>
{% load staticfiles %}
<!--[if IE 8]>			<html class="ie ie8"> <![endif]-->
<!--[if IE 9]>			<html class="ie ie9"> <![endif]-->
<!--[if gt IE 9]><!-->	<html> <!--<![endif]-->
<head>
<meta charset="utf-8" />
<title>Colegio Amelia Gallegos</title>
<link href="{% static 'assets/plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
</head>

<style>
h1 {
	text-align: center
}
</style>

<body>
	<div class = "col-md-10">
		<h1> Colegio Amelia Gallegos </h1>
		<h3> {{alumno.nombre_completo|upper}} - <small>{{periodo.nombre_parcial}} / {{periodo.nombre_quimestre}} </small> </h2>
	</div>
	<div class = "row">
	<div class = "col-md-12">
		<table class ="table table-bordered table-striped">
			<thead>
			<tr>
				<th>Clase</th>
				<th>Tareas</th>
				<th>Actividades Individuales</th>
				<th>Actividades Grupales</th>
				<th>Lecciones</th>
				<th>Pruebas</th>
				<th><i>Promedio</i></th>
			</tr>
			</thead>
			<tbody>
				{% for nota in notas %}
					<tr>
						<td>{{nota.clase}}</td>
						<td class = "nota_tareas" data-nota = "{{nota.tareas}}" >{{nota.tareas}}</td>
						<td class = "nota_actividades_i" data-nota = "{{nota.act_ind}}" >{{nota.act_ind}}</td>
						<td class = "nota_actividades_g" data-nota = "{{nota.act_gru}}" >{{nota.act_gru}}</td>
						<td class = "nota_lecciones" data-nota = "{{nota.lecciones}}">{{nota.lecciones}}</td>
						<td class = "nota_pruebas" data-nota = "{{nota.pruebas}}" >{{nota.pruebas}}</td>
						<td class = "promedio" data-nota = "{{nota.promedio}}" >
						<i>{{nota.promedio}}</i></td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
	</div>
</body>
</html>

academica/templates/academica/alumnos.html
{% extends 'base_sisacademico.html' %}
{% load staticfiles  %}

{% block content %}
<div class = "col-md-10 col-md-offset-1">
	<h2>
		Búsqueda de Notas de Periodos por Alumno <br>		
		<small>
		Introduzca el número de cédula, el periodo y el nivel del cual desea consultar las notas. 
		</small>
	</h2>
	{% if tipo == 'quimestral' %}
		<p> <a href="{% url 'sisacademico:alumnos' 'periodo' %}">Reporte de Notas por Periodo</a></p>
	{% else %}
		<p> <a href="{% url 'sisacademico:alumnos' 'quimestral' %}">Reporte de Notas Quimestrales</a></p>
	{% endif %}
	<hr>
</div>
<div class = "col-md-6 col-md-offset-2">
	<p id ="errores" class ="well hidden"> </p>
	{% if tipo == 'quimestral' %}
	<form id="form_alumnos" role = "form" action = "{% url 'sisacademico:reporte_quimestre' %}" method="get">
	{% else %}
	<form id="form_alumnos" role = "form" action = "{% url 'sisacademico:alumno_notas' %}" method="get">
	{% endif %}
		<div class = "form-group">
			{{form}}
		</div>
		<input id="form_enviar" class = "btn btn-default" type="submit" value="Enviar"/>
	</form>
</div>

<script>

$(document).ready(function(){
	$("#form_enviar").on("click", function(e){
		e.preventDefault();
		var cedula = $("#cedula").val();
		if (cedula == parseInt(cedula, 10)){
			$("#form_alumnos").submit();
		}
		else{
			$("#errores").removeClass("hidden").text("Por favor, escribe una cédula válida");
		}
	});
})

</script
{% endblock content %}

academica/templates/academica/cambiar_password.html
{% extends 'base_sisacademico.html' %}

{% block content %}
<div class = "col-md-6 col-md-offset-2">
	<form method="post">
	{% csrf_token %}
	{{form.non_field_errors}}
	<div class = "form-group">
		<label class = "control-label" for="texto"> Contraseña Actual </label>
		{{form.old_password}}
		{{form.old_password.errors}}
	</div>
	<div class = "form-group">
		<label class = "control-label" for="texto"> Contraseña Nueva </label>
		{{form.new_password1}}
		{{form.new_password1.errors}}
	</div>
	<div class = "form-group">
		<label class = "control-label" for="texto"> Contraseña Nueva, repítela por seguridad</label>
		{{form.new_password2}}
		{{form.new_password2.errors}}
	</div>
	<input class = "btn pull-right" type = "submit" value ="enviar"/>
	</form>
</div>
{% endblock content %}

academica/templates/academica/clase_periodos.html
{% extends 'base_sisacademico.html' %}

{% block content %}
	<div class = "row">
		<div class = "col-md-8 col-md-offset-2">
			<h2>{{clase.nombre}} - {{clase.nivel}}</h2>
		</div>
	</div>
	<div class = "row">
		<hr>
		<div class = "col-md-5 col-md-offset-2">
			<div class="list-group">
				<a href="" class = "list-group-item disabled">Periodos</a>
				{% for periodo in periodos %}
					<a href="{% url 'sisacademico:clase_alumnos' clase.id periodo.id %}" class = "list-group-item">{{periodo.nombre_periodo}}</a>
				{% endfor %}
			</div>
		</div>
	</div>
{% endblock content %}

academica/templates/academica/form_perfil_profesor.html
{% extends 'base_sisacademico.html' %}

{% block content %}
<div class = "row">
	<div class = "col-md-8 col-md-offset-2">
		<form id = "form_perfil_profesor" class="form-horizontal" action = "{% url 'academica:perfil_profesor' %}" method = "post">
		{% csrf_token %}
		{{form_editar_perfil.as_table}}
		<input class = "btn pull-right" type = "submit" value ="enviar"/>
		<span class ="help-block">Si los campos son incorrectos, por favor acercarse a secretaría</span> 
		</form>
	</div>
</div>
<div class = "row">
	<div class = "col-md-8 col-md-offset-2">
		<ul class = "list-group">
			<li class = "list-group-item"><strong>Usuario</strong>: {{user.username}}</li>
			<li class = "list-group-item"><strong>Nombre</strong>: {{user.first_name}}</li>
			<li class = "list-group-item"><strong>Apellido</strong>: {{user.last_name}}</li>
			<li class = "list-group-item"><strong>Titulo</strong>: {{perfil_actual.titulo}}</li>
			<li class = "list-group-item"><strong>Contacto</strong>: {{perfil_actual.num_contacto}}</li>
			<li class = "list-group-item"><strong>Nivel</strong>: {{perfil_actual.nivel.nombre}}</li>
		</ul>
	</div>
</div>
<div class = "col-md-10">
<a class = "pull-right" href="{% url 'academica:cambiar_password' %}">Cambiar contraseña</a>
</div>
{% endblock content%}

academica/templates/academica/lista_clases.html
{% extends 'base_sisacademico.html' %}

{% block content %}
<div class = "col-md-8 col-md-offset-2">
<h1> Clases </h1>
	<div class="list-group">
	{% for clase in clases_profesor %}
	  <a href="{% url 'sisacademico:clase_periodos' clase.id %}" class="list-group-item">
	  {{clase.nombre}} - {{clase.nivel}}</a>
	{% endfor %}
	</div>
</div>
{% endblock content %}

academica/templates/academica/matricular_grupo.html
{% extends 'admin/base_site.html' %}

{% block content %}

<form method="post" action="{% url 'sisacademico:matricular_grupo' %}" >
	{% csrf_token %}

	{{form}}
	<br>
	<input class ="btn btn-success"  type="submit" value ="matricular alumnos">
</form>

<h3> Matricular los siguientes alumnos: </h3>

	{% for a in alumnos %}		
		<p class ="well"> {{a.apellido|upper}} {{a.nombre|upper}}</p>
	{% endfor %}

{% endblock content %}

academica/templates/academica/matriculas_creadas.html
{% extends 'admin/base_site.html' %}

{% block content %}

<h3> Se crearon las siguientes matrículas <br> <small> te redigiremos a la página principal en unos segundos </small> </h3>

{% for m in matriculas_creadas %}

	<p class = "well">
		Alumno: {{m.alumno.apellido|upper}} {{m.alumno.nombre|upper}} <br>
		Nivel: {{m.nivel.nombre}} | {{m.ano_lectivo}}
	</p>

{% endfor %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script>
$(document).ready(function(){

	window.setTimeout(function(){
		window.location = "{% url 'admin:index' %}";
	}, 9000);
});
</script>

{% endblock content %}

academica/templates/academica/password_changed.html
{% extends 'base_sisacademico.html' %}

{% block content %}

<p> Contraseña cambiada </p>

{% endblock content %}

academica/templates/academica/reporte_matricula.html
<!DOCTYPE html>
{% load staticfiles %}
<!--[if IE 8]>			<html class="ie ie8"> <![endif]-->
<!--[if IE 9]>			<html class="ie ie9"> <![endif]-->
<!--[if gt IE 9]><!-->	<html> <!--<![endif]-->
<head>
<meta charset="utf-8" />
<title>Colegio Amelia Gallegos</title>
<link href="{% static 'assets/plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
</head>

<body>
	{% for matricula in matriculas %}
		<div class="container-fluid">
			<br>
			<div class="row">
				<div class="col-md-12">
					<div class ="row">
						<div class ="col-md-9">
							<h3 class ="well">
								Matrícula <strong> {{matricula.alumno.nombre_completo}} </strong>.
							</h3>
						</div>
						<div class ="col-md-3">
							<img class ="pull-right" src="{% static 'assets/images/logo.png' %}" height="50" alt=""/>
						</div>
					</div>
					<div class="panel panel-info">
						<div class="panel-heading">
							<h3 class="panel-title">
								Año: {{matricula.ano_lectivo}}. <br>
								Nivel: {{matricula.nivel.nombre}}. </br>		
								
							</h3>
						</div>
						<div class="panel-body">
							<strong> Datos del alumno </strong> <br>
							Cédula: {{matricula.alumno.cedula}} <br>
							Nombres: {{matricula.alumno.nombre}} <br>
							Apellidos: {{matricula.alumno.apellido}} {{matricula.alumno.segundo_apellido}} <br>
							Fecha de Nacimiento: {{matricula.alumno.fecha_nacimiento}} <br>
						</div>
						<div class="panel-footer">
							ID de Matrícula: {{matricula.id}}.
						</div>
					</div>
				</div>
			</div>
		</div>
		<hr>
	{% endfor %}
</body>

academica/templates/academica/reporte_quimestral.html
<!DOCTYPE html>
{% load staticfiles %}
<!--[if IE 8]>			<html class="ie ie8"> <![endif]-->
<!--[if IE 9]>			<html class="ie ie9"> <![endif]-->
<!--[if gt IE 9]><!-->	<html> <!--<![endif]-->
<head>
<meta charset="utf-8" />
<title>Colegio Amelia Gallegos</title>
<link href="{% static 'assets/plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
</head>

<style>
h1 {
	text-align: center
}
</style>

<body>
	<div class = "col-md-10">
		<h1> Colegio Amelia Gallegos </h1>
		<h3> {{alumno.nombre_completo|upper}} - <small> Notas / {{quimestre}} Quimestre / {{ano}} </small> </h2>
	</div>
	<div class = "row">
	<div class = "col-md-12">
		<table class ="table table-bordered table-striped">
			<thead>
			<tr>
				<th>Clase</th>
				<th>Primer Parcial</th>
				<th>Segundo Parcial</th>
				<th>Tercer Parcial</th>
				<th>Promedio Quimestral</th>
			</tr>
			</thead>
			<tbody>
				{% for nota in notas %}
					<tr>
						<td>{{nota.0.nombre|upper}}</td>
						<td>{{nota.1.1}}</td>
						<td>{{nota.2.1}}</td>
						<td>{{nota.3.1}}</td>
						<td>{{nota.4}}</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
	</div>
</body>
</html>